interface DataTodo {
  avatar: string;
  isRemove: boolean;
  title: string;
  createAt: Date;
  isDone: boolean;
  description: string;
  userName: string;
}

const dataTodo: DataTodo[] = [
  {
    avatar: "nguoi-1.png",
    isRemove: false,
    title: "Viết email cho khách hàng",
    createAt: new Date(),
    isDone: true,
    description: "Viết email để trả lời các câu hỏi của khách hàng.",
    userName: "Nguyễn Văn A",
  },
  {
    avatar: "nguoi-2.png",
    isRemove: true,
    title: "Đi mua thực phẩm",
    createAt: new Date(),
    isDone: false,
    description: "Mua thực phẩm và thực hiện thanh toán.",
    userName: "Nguyễn Thị B",
  },
  {
    avatar: "nguoi-3.png",
    isRemove: false,
    title: "Học tiếng Anh",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập tiếng Anh cho bài kiểm tra.",
    userName: "Trần Văn C",
  },
  {
    avatar: "nguoi-4.png",
    isRemove: true,
    title: "Thiết kế hình ảnh",
    createAt: new Date(),
    isDone: true,
    description: "Tạo hình ảnh sáng tạo cho dự án thiết kế.",
    userName: "Lê Thị D",
  },
  {
    avatar: "nguoi-5.png",
    isRemove: false,
    title: "Lập trình ứng dụng",
    createAt: new Date(),
    isDone: true,
    description: "Viết mã nguồn cho ứng dụng mới.",
    userName: "Phạm Văn E",
  },
  {
    avatar: "nguoi-6.png",
    isRemove: false,
    title: "Chăm sóc cây cỏ",
    createAt: new Date(),
    isDone: false,
    description: "Tưới nước và bón phân cho cây cỏ trong vườn.",
    userName: "Hoàng Thị F",
  },
  {
    avatar: "nguoi-7.png",
    isRemove: true,
    title: "Thực hiện bài tập thể dục",
    createAt: new Date(),
    isDone: true,
    description: "Tập thể dục hàng ngày để duy trì sức khỏe.",
    userName: "Trịnh Văn G",
  },
  {
    avatar: "nguoi-8.png",
    isRemove: false,
    title: "Viết bài luận",
    createAt: new Date(),
    isDone: false,
    description: "Viết bài luận về một chủ đề quan trọng.",
    userName: "Phan Thị H",
  },
  {
    avatar: "nguoi-9.png",
    isRemove: true,
    title: "Nấu ăn cho gia đình",
    createAt: new Date(),
    isDone: true,
    description: "Nấu bữa tối cho gia đình.",
    userName: "Bùi Văn I",
  },
  {
    avatar: "nguoi-10.png",
    isRemove: false,
    title: "Làm việc từ xa",
    createAt: new Date(),
    isDone: true,
    description: "Hoàn thành công việc từ xa cho công ty.",
    userName: "Ngô Thị K",
  },
  {
    avatar: "nguoi-11.png",
    isRemove: false,
    title: "Làm việc với tài liệu",
    createAt: new Date(),
    isDone: true,
    description: "Kiểm tra và sửa các tài liệu văn bản.",
    userName: "Trương Văn L",
  },
  {
    avatar: "nguoi-12.png",
    isRemove: true,
    title: "Chơi thể thao",
    createAt: new Date(),
    isDone: false,
    description: "Tham gia một trận đấu bóng đá cùng bạn bè.",
    userName: "Lý Thị M",
  },
  {
    avatar: "nguoi-13.png",
    isRemove: false,
    title: "Học piano",
    createAt: new Date(),
    isDone: false,
    description: "Tập trung vào việc học chơi piano.",
    userName: "Đinh Văn N",
  },
  {
    avatar: "nguoi-14.png",
    isRemove: true,
    title: "Dự án nghiên cứu",
    createAt: new Date(),
    isDone: true,
    description: "Tiến hành dự án nghiên cứu về khoa học máy tính.",
    userName: "Lưu Thị P",
  },
  {
    avatar: "nguoi-15.png",
    isRemove: false,
    title: "Viết blog",
    createAt: new Date(),
    isDone: true,
    description: "Viết bài blog về du lịch.",
    userName: "Phạm Thanh Q",
  },
  {
    avatar: "nguoi-16.png",
    isRemove: false,
    title: "Trồng cây cảnh",
    createAt: new Date(),
    isDone: false,
    description: "Trồng cây cảnh mới trong vườn.",
    userName: "Nguyễn Minh R",
  },
  {
    avatar: "nguoi-17.png",
    isRemove: true,
    title: "Học lập trình web",
    createAt: new Date(),
    isDone: true,
    description: "Học về phát triển ứng dụng web.",
    userName: "Trần Đức S",
  },
  {
    avatar: "nguoi-18.png",
    isRemove: false,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: false,
    description: "Đọc một cuốn sách mới.",
    userName: "Phan Quốc T",
  },
  {
    avatar: "nguoi-19.png",
    isRemove: true,
    title: "Nấu bữa trưa",
    createAt: new Date(),
    isDone: true,
    description: "Nấu bữa trưa cho gia đình.",
    userName: "Bùi Thị U",
  },
  {
    avatar: "nguoi-20.png",
    isRemove: false,
    title: "Dự án phát triển ứng dụng di động",
    createAt: new Date(),
    isDone: true,
    description: "Phát triển ứng dụng di động mới.",
    userName: "Nguyễn Đức V",
  },
];

export default dataTodo;
