import { DataTodo } from "./type";

export const dataTodo: DataTodo[] = [
  {
    avatar: "https://i.pravatar.cc/150?img=1",
    isRemove: false,
    title: "Viết email cho khách hàng",
    createAt: new Date(),
    isDone: true,
    description: "Viết email để trả lời các câu hỏi của khách hàng.",
    userName: "Nguyễn Anh Tuấn",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=2",
    isRemove: true,
    title: "Đi mua thực phẩm",
    createAt: new Date(),
    isDone: false,
    description: "Mua thực phẩm và thực hiện thanh toán.",
    userName: "Trần Thị Hương",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=3",
    isRemove: false,
    title: "Học tiếng Anh",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập tiếng Anh cho bài kiểm tra.",
    userName: "Lê Minh Đức",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=4",
    isRemove: true,
    title: "Thiết kế hình ảnh",
    createAt: new Date(),
    isDone: true,
    description: "Tạo hình ảnh sáng tạo cho dự án thiết kế.",
    userName: "Phạm Thị Ngọc",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=5",
    isRemove: false,
    title: "Lập trình ứng dụng",
    createAt: new Date(),
    isDone: true,
    description: "Viết mã nguồn cho ứng dụng mới.",
    userName: "Hoàng Văn Nam",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=6",
    isRemove: false,
    title: "Chăm sóc cây cỏ",
    createAt: new Date(),
    isDone: false,
    description: "Tưới nước và bón phân cho cây cỏ trong vườn.",
    userName: "Nguyễn Thị Lan",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=7",
    isRemove: true,
    title: "Thực hiện bài tập thể dục",
    createAt: new Date(),
    isDone: true,
    description: "Tập thể dục hàng ngày để duy trì sức khỏe.",
    userName: "Trần Minh Hòa",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=8",
    isRemove: false,
    title: "Viết bài luận",
    createAt: new Date(),
    isDone: false,
    description: "Viết bài luận về một chủ đề quan trọng.",
    userName: "Lê Thị Phương",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=9",
    isRemove: true,
    title: "Nấu ăn cho gia đình",
    createAt: new Date(),
    isDone: true,
    description: "Nấu bữa tối cho gia đình.",
    userName: "Phạm Hữu Long",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=10",
    isRemove: false,
    title: "Làm việc từ xa",
    createAt: new Date(),
    isDone: true,
    description: "Hoàn thành công việc từ xa cho công ty.",
    userName: "Nguyễn Thị Quỳnh",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=11",
    isRemove: false,
    title: "Làm việc với tài liệu",
    createAt: new Date(),
    isDone: true,
    description: "Kiểm tra và sửa các tài liệu văn bản.",
    userName: "Trần Văn Hùng",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=12",
    isRemove: true,
    title: "Chơi thể thao",
    createAt: new Date(),
    isDone: false,
    description: "Tham gia một trận đấu bóng đá cùng bạn bè.",
    userName: "Lê Thị Mai",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=13",
    isRemove: false,
    title: "Học piano",
    createAt: new Date(),
    isDone: false,
    description: "Tập trung vào việc học chơi piano.",
    userName: "Phạm Văn Hoàng",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=14",
    isRemove: true,
    title: "Dự án nghiên cứu",
    createAt: new Date(),
    isDone: true,
    description: "Tiến hành dự án nghiên cứu về khoa học máy tính.",
    userName: "Hoàng Thị Thu",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=15",
    isRemove: false,
    title: "Viết blog",
    createAt: new Date(),
    isDone: true,
    description: "Viết bài blog về du lịch.",
    userName: "Nguyễn Văn Hải",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=16",
    isRemove: false,
    title: "Trồng cây cảnh",
    createAt: new Date(),
    isDone: false,
    description: "Trồng cây cảnh mới trong vườn.",
    userName: "Trần Thị Quỳnh",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=17",
    isRemove: true,
    title: "Học lập trình web",
    createAt: new Date(),
    isDone: true,
    description: "Học về phát triển ứng dụng web.",
    userName: "Lê Thị Ánh",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=18",
    isRemove: false,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: false,
    description: "Đọc một cuốn sách mới.",
    userName: "Phạm Văn Sơn",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=19",
    isRemove: true,
    title: "Nấu bữa trưa",
    createAt: new Date(),
    isDone: true,
    description: "Nấu bữa trưa cho gia đình.",
    userName: "Hoàng Thị Thảo",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=20",
    isRemove: false,
    title: "Dự án phát triển ứng dụng di động",
    createAt: new Date(),
    isDone: true,
    description: "Phát triển ứng dụng di động mới.",
    userName: "Nguyễn Thị Uyên",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=21",
    isRemove: false,
    title: "Thiết kế đồ họa",
    createAt: new Date(),
    isDone: true,
    description: "Tạo đồ họa và thiết kế cho dự án.",
    userName: "Trần Văn Quang",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=22",
    isRemove: true,
    title: "Học lập trình Python",
    createAt: new Date(),
    isDone: false,
    description: "Học lập trình Python và viết mã nguồn.",
    userName: "Lê Văn Tùng",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=23",
    isRemove: false,
    title: "Dự án nghiên cứu y tế",
    createAt: new Date(),
    isDone: false,
    description: "Tiến hành nghiên cứu về y tế.",
    userName: "Phạm Thị Yến",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=24",
    isRemove: true,
    title: "Tìm hiểu lịch sử",
    createAt: new Date(),
    isDone: true,
    description: "Tìm hiểu về lịch sử quê hương.",
    userName: "Hoàng Văn Hùng",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=25",
    isRemove: false,
    title: "Lập kế hoạch du lịch",
    createAt: new Date(),
    isDone: true,
    description: "Lập kế hoạch cho chuyến du lịch cuối tuần.",
    userName: "Nguyễn Thị Ngân",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=26",
    isRemove: false,
    title: "Học nghệ thuật",
    createAt: new Date(),
    isDone: false,
    description: "Tham gia các khóa học nghệ thuật.",
    userName: "Trần Văn Hiệp",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=27",
    isRemove: false,
    title: "Chơi guitar",
    createAt: new Date(),
    isDone: true,
    description: "Tập chơi guitar và sáng tác âm nhạc.",
    userName: "Lê Văn Duy",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=28",
    isRemove: true,
    title: "Viết sách",
    createAt: new Date(),
    isDone: true,
    description: "Viết một cuốn sách mới về lịch sử.",
    userName: "Phạm Thị Hoa",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=29",
    isRemove: false,
    title: "Làm việc với dự án nghị quyết",
    createAt: new Date(),
    isDone: true,
    description: "Tham gia vào việc triển khai dự án nghị quyết quan trọng.",
    userName: "Hoàng Văn Mạnh",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=30",
    isRemove: true,
    title: "Chơi cầu lông",
    createAt: new Date(),
    isDone: false,
    description: "Chơi cầu lông cùng bạn bè vào cuối tuần.",
    userName: "Nguyễn Thị Thủy",
  },
  {
    avatar: "https://i.pravatar.cc/150?img=31",
    isRemove: false,
    title: "Thiết kế đồ họa",
    createAt: new Date(),
    isDone: false,
    description: "Tạo đồ họa cho dự án mới.",
    userName: "Bùi Hoàng Vinh",
  },
];
